"""Scaffold templates for the ``ghfun repo bootstrap`` command."""

from __future__ import annotations

WORKFLOW_TEMPLATE: str = """\
name: "ghfun-agent"

on:
  workflow_dispatch:
    inputs:
      task_id:
        description: "Issue or task identifier (e.g. #42)"
        required: true
        type: string
      task_type:
        description: "Kind of work the agent should perform"
        required: true
        type: choice
        options:
          - docs
          - code
          - tests
          - seed
          - ci
      instructions:
        description: "Free-form instructions for the agent"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  agent-task:
    name: "Run agent task (${{ inputs.task_type }})"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Display task info
        run: |
          echo "Task ID:       ${{ inputs.task_id }}"
          echo "Task type:     ${{ inputs.task_type }}"
          echo "Instructions:  ${{ inputs.instructions }}"

      - name: Execute task
        run: |
          set -euo pipefail
          case "${{ inputs.task_type }}" in
            docs)
              echo "Scaffolding docs directory..."
              mkdir -p docs
              if [ ! -f docs/README.md ]; then
                echo "# Documentation" > docs/README.md
                echo "" >> docs/README.md
                echo "Project documentation lives here." >> docs/README.md
              fi
              ;;
            code)
              echo "Running code generation scaffolding..."
              mkdir -p src
              ;;
            tests)
              echo "Running linters and test scaffolding..."
              pip install --quiet ruff pytest
              ruff check . --fix || true
              mkdir -p tests
              if [ ! -f tests/__init__.py ]; then
                touch tests/__init__.py
              fi
              ;;
            seed)
              echo "Creating seed / starter files..."
              mkdir -p src tests docs
              touch src/__init__.py tests/__init__.py
              if [ ! -f README.md ]; then
                echo "# $(basename $GITHUB_REPOSITORY)" > README.md
              fi
              ;;
            ci)
              echo "Setting up CI configuration..."
              mkdir -p .github/workflows
              ;;
            *)
              echo "Unknown task type: ${{ inputs.task_type }}"
              exit 1
              ;;
          esac

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "ghfun/task-${{ inputs.task_id }}-${{ inputs.task_type }}"
          title: "ghfun: ${{ inputs.task_type }} task for ${{ inputs.task_id }}"
          body: |
            ## Agent Task Result

            | Field | Value |
            |-------|-------|
            | **Task ID** | `${{ inputs.task_id }}` |
            | **Type** | `${{ inputs.task_type }}` |
            | **Instructions** | ${{ inputs.instructions || '_none_' }} |

            ---
            _Automatically generated by the ghfun-agent workflow._
          commit-message: "ghfun(${{ inputs.task_type }}): ${{ inputs.task_id }}"
          labels: ghfun
"""

ISSUE_TEMPLATE: str = """\
---
name: "ghfun task"
about: "Create a task for the gh-agent-funhouse workflow"
title: "[ghfun] "
labels:
  - ghfun
assignees: []
---

## Task Description

<!-- Describe the task the agent should perform. -->

## Task Type

<!-- One of: docs, code, tests, seed, ci -->
- [ ] docs
- [ ] code
- [ ] tests
- [ ] seed
- [ ] ci

## Instructions

<!-- Provide any additional instructions or context for the agent. -->

## Acceptance Criteria

- [ ] Task completed successfully
- [ ] Pull request created with results
- [ ] No regressions introduced
"""

MISSION_CONTROL_TEMPLATE: str = """\
# 🎯 Mission Control

> Central tracking document for gh-agent-funhouse operations in this repository.

## Status

| Metric | Value |
|--------|-------|
| **Active Tasks** | 0 |
| **Completed Tasks** | 0 |
| **Pending Reviews** | 0 |

## Recent Activity

<!-- Automatically updated by ghfun workflows. -->

| Date | Task | Type | Status | PR |
|------|------|------|--------|----|
| _No activity yet_ | | | | |

## Configuration

- **Workflow:** `.github/workflows/ghfun-agent.yml`
- **Issue Template:** `.github/ISSUE_TEMPLATE/ghfun-task.md`
- **Tracking Doc:** `docs/MISSION_CONTROL.md`

## Quick Start

1. Create a new issue using the **ghfun task** template
2. Run `ghfun mission launch <issue-number>` to dispatch the agent
3. Monitor progress with `ghfun dashboard` or check the Actions tab

---
_Managed by [gh-agent-funhouse](https://github.com/gh-agent-funhouse)._
"""
